# Generated by Django 3.2.7 on 2021-09-07 11:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_notebook_smatphone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Castomer',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Smatphone',
            new_name='Smartphone',
        ),
    ]
