# Generated by Django 3.2.7 on 2021-09-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_smartphone_sd'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='for_anonimous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
    ]
