# Generated by Django 3.1 on 2021-09-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20210915_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='for_anonimous_user',
            field=models.BooleanField(default=True),
        ),
    ]
