# Generated by Django 3.1 on 2021-09-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20210915_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='for_anonimous_user',
        ),
        migrations.AddField(
            model_name='cart',
            name='for_anonymous_user',
            field=models.BooleanField(default=False),
        ),
    ]
